version: '2.1'
services:
  zookeeper:
    image: zookeeper:3.3.6
    ports:
    - 2181:2181
    environment:
      ZOO_STANDALONE_ENABLED: "TRUE"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka:1.1.0
    depends_o